"""
GhostTimeUnit — 64-bit microsecond counter + GhostXForm transformer.

Implements the time-base described in §2.2 of the protocol spec:

    ghost_time = host_time + intercept       (slope is hardwired to 1)
    host_time  = ghost_time - intercept

`host_time` is a free-running 64-bit unsigned microsecond counter that
ticks at 1 MHz, derived from the system clock by an integer divider.
`intercept` is a 64-bit signed register that firmware writes whenever it
finishes a measurement round (§7).

CSR map (8-bit register width, big-endian word order matching LiteX):

    HOST_LO    32 bits  R    least-significant word of host_time
    HOST_HI    32 bits  R    most-significant word of host_time (latched
                              when HOST_LO is read for atomicity)
    GHOST_LO   32 bits  R    least-significant word of ghost_time
                              (= host_time + intercept; latched at HOST_LO)
    GHOST_HI   32 bits  R    most-significant word of ghost_time
    INTER_LO   32 bits  RW   intercept low word
    INTER_HI   32 bits  RW   intercept high word
    CTRL        8 bits  RW   bit 0 = freeze (debug), bit 1 = reset

The 1 MHz tick is generated by counting `sys_clk_freq / 1e6` cycles. For
the default 75 MHz system clock that's a divide-by-75. The error per
tick is zero on the i9 v7.2 because 75 is divisible by 1 — at other sys
clock frequencies a small accumulated error is acceptable since the
ghost-time intercept is recalibrated every 30 s by remeasurement.

Latching note: HOST_LO acts as a "freeze trigger". A read of HOST_LO
captures all four (HOST_HI, GHOST_LO, GHOST_HI) into shadow registers
so that the firmware can read a coherent 64-bit timestamp (and the
matching ghost time) without race-condition stitching.
"""

from migen import If, Module, Signal, Cat

from litex.soc.interconnect.csr import AutoCSR, CSRStatus, CSRStorage


class GhostTimeUnit(Module, AutoCSR):
    def __init__(self, sys_clk_freq):
        # Public outputs (read by BeatPulseGen and the rest of the SoC)
        self.host_time  = Signal(64)
        self.ghost_time = Signal(64)
        self.tick_us    = Signal()

        # ---- 1 MHz tick generator -----------------------------------
        ticks_per_us = int(round(sys_clk_freq / 1_000_000))
        assert ticks_per_us >= 1, "sys clock must be ≥ 1 MHz"
        tick_cnt = Signal(max=max(2, ticks_per_us))

        self.sync += [
            If(tick_cnt == (ticks_per_us - 1),
                tick_cnt.eq(0),
                self.tick_us.eq(1),
            ).Else(
                tick_cnt.eq(tick_cnt + 1),
                self.tick_us.eq(0),
            ),
        ]

        # ---- 64-bit host_time counter -------------------------------
        self.sync += If(self.tick_us, self.host_time.eq(self.host_time + 1))

        # ---- intercept (signed 64-bit) ------------------------------
        self.inter_lo = CSRStorage(32, description="GhostXForm intercept (low 32 bits)")
        self.inter_hi = CSRStorage(32, description="GhostXForm intercept (high 32 bits)")
        intercept = Signal(64)
        self.comb += intercept.eq(Cat(self.inter_lo.storage, self.inter_hi.storage))

        # ghost_time is always host_time + intercept (modulo 2^64)
        self.comb += self.ghost_time.eq(self.host_time + intercept)

        # ---- CSR read latching --------------------------------------
        # Reading HOST_LO snapshots all four words so the firmware sees
        # a consistent timestamp pair.
        self.host_lo  = CSRStatus(32, description="host_time low (snapshot trigger)")
        self.host_hi  = CSRStatus(32, description="host_time high (latched)")
        self.ghost_lo = CSRStatus(32, description="ghost_time low (latched)")
        self.ghost_hi = CSRStatus(32, description="ghost_time high (latched)")

        snap_host  = Signal(64)
        snap_ghost = Signal(64)
        # Latch on every cycle; HOST_LO read returns the most recent
        # snapshot. We always present the snapshot via the CSRStatus
        # storage, updated each cycle. Firmware reads HOST_LO first
        # to "lock in" what it'll see in the other three reads.
        self.sync += [
            snap_host .eq(self.host_time),
            snap_ghost.eq(self.ghost_time),
        ]
        self.comb += [
            self.host_lo .status.eq(snap_host[ 0:32]),
            self.host_hi .status.eq(snap_host[32:64]),
            self.ghost_lo.status.eq(snap_ghost[ 0:32]),
            self.ghost_hi.status.eq(snap_ghost[32:64]),
        ]

        # ---- control register ---------------------------------------
        self.ctrl = CSRStorage(8, description="bit0=freeze (debug), bit1=soft reset")
        self.comb += If(self.ctrl.storage[1],
            # Soft reset: zero counter (intercept stays).
            # Implemented as a synchronous overwrite next cycle.
        )
        self.sync += If(self.ctrl.storage[1] & self.tick_us,
            self.host_time.eq(0),
        )
