"""
LinkFPGASoC: top-level LiteX SoC for the Colorlight i9 v7.2.

Composes:
  * VexRiscv `standard` softcore @ 75 MHz
  * LiteDRAM SDR controller (board's onboard SDRAM)
  * LiteEth MAC + UDP stack on PHY0 (RGMII)
  * The four LinkFPGA custom modules:
      - GhostTimeUnit         (litex_soc.ghost_time)
      - LinkPacketFilter      (litex_soc.link_filter)
      - BeatPulseGen          (litex_soc.beat_pulse)
      - TDM16Core × N         (litex_soc.tdm)

The number of TDM16 ports is configurable via the `num_tdm_ports`
constructor parameter (default 2). Of those, the first
`num_physical_tdm_ports` are exposed on real HUB75 pins; any extras are
**virtual** — they have a TDM16 register interface and a sample buffer
in SDRAM, but no associated physical I/O. Virtual ports are useful for
software-only audio routing between Link-Audio peers.

Each module is a `Module` with a CSR bank that is auto-exposed via the
LiteX CSR bus, so the firmware can poke registers via
`csr_read_simple`/`csr_write_simple`.
"""

from migen import ClockDomain, ClockSignal, Instance, Module, Signal

from litex.build.io import DDROutput
from litex.soc.cores.clock import ECP5PLL
from litex.soc.integration.soc_core import SoCCore

from liteeth.phy.ecp5rgmii import LiteEthPHYRGMII

from .ghost_time import GhostTimeUnit
from .link_filter import LinkPacketFilter
from .beat_pulse import BeatPulseGen
from .tdm import TDM16Core
from .platform_i9 import MAX_PHYSICAL_TDM_PORTS


class _CRG(Module):
    """Clock & reset generator. Produces:
       - sys     (configurable, default 75 MHz)
       - sys_ps  (sys, 180° phase, used to clock the SDRAM pad)
       - audio   (24.576 MHz, the TDM master clock — separate PLL)

    The ECP5 PLL only supports related-frequency outputs from a single
    VCO, so the audio clock is generated by a *second* PLL. This is the
    same trick the upstream `colorlight_i5` target uses for video.
    """

    def __init__(self, platform, sys_clk_freq):
        self.clock_domains.cd_sys    = ClockDomain()
        self.clock_domains.cd_sys_ps = ClockDomain()
        self.clock_domains.cd_audio  = ClockDomain()

        clk25 = platform.request("clk25")
        rst_n = platform.request("cpu_reset_n")

        # ---- main system PLL ---------------------------------------
        self.submodules.pll = pll = ECP5PLL()
        self.comb += pll.reset.eq(~rst_n)
        pll.register_clkin(clk25, 25e6)
        pll.create_clkout(self.cd_sys,    sys_clk_freq)
        pll.create_clkout(self.cd_sys_ps, sys_clk_freq, phase=180)

        # ---- audio PLL ---------------------------------------------
        self.submodules.audio_pll = apll = ECP5PLL()
        self.comb += apll.reset.eq(~rst_n)
        apll.register_clkin(clk25, 25e6)
        apll.create_clkout(self.cd_audio, 24.576e6, margin=5e-3)

        # SDRAM pad clock — DDR output of sys_ps
        self.specials += DDROutput(1, 0, platform.request("sdram_clock"),
                                   ClockSignal("sys_ps"))


class LinkFPGASoC(SoCCore):
    """Top-level SoC. Inherit from SoCCore so we get the standard LiteX
    BIOS slot, CSR bus, IRQ aggregator, etc.

    Args:
        platform: A `colorlight_i9.Platform` already extended via
            `litex_soc.platform_i9.attach_link_io()`.
        sys_clk_freq: System clock frequency in Hz (default 75 MHz).
        num_tdm_ports: Total number of TDM16 ports to instantiate
            (physical + virtual). Default 2.
        num_physical_tdm_ports: How many of those should be wired to
            real HUB75 pins. The remaining `num_tdm_ports -
            num_physical_tdm_ports` ports are instantiated as virtual
            ports (no I/O pins).
        with_second_eth: Bring up the second GbE PHY (default off).
    """

    def __init__(self, platform,
                 sys_clk_freq          = int(75e6),
                 num_tdm_ports         = 2,
                 num_physical_tdm_ports= 2,
                 with_second_eth       = False):

        if num_physical_tdm_ports > num_tdm_ports:
            raise ValueError(
                "num_physical_tdm_ports cannot exceed num_tdm_ports")
        if num_physical_tdm_ports > MAX_PHYSICAL_TDM_PORTS:
            raise ValueError(
                f"num_physical_tdm_ports cannot exceed "
                f"MAX_PHYSICAL_TDM_PORTS ({MAX_PHYSICAL_TDM_PORTS})")

        self.num_tdm_ports          = num_tdm_ports
        self.num_physical_tdm_ports = num_physical_tdm_ports
        self.num_virtual_tdm_ports  = num_tdm_ports - num_physical_tdm_ports

        # ----- core ----------------------------------------------------
        SoCCore.__init__(self, platform,
            clk_freq             = sys_clk_freq,
            cpu_type             = "vexriscv",
            cpu_variant          = "standard+debug",
            ident                = "LinkFPGA / Ableton Link in hardware",
            ident_version        = True,
            integrated_rom_size  = 0x10000,    # 64 KiB BIOS+early firmware
            integrated_sram_size = 0x4000,     # 16 KiB scratch
            uart_name            = "serial",
        )

        self.submodules.crg = _CRG(platform, sys_clk_freq)

        # ----- SDRAM ---------------------------------------------------
        from litedram.modules import M12L64322A
        from litedram.phy import GENSDRPHY
        self.submodules.sdrphy = GENSDRPHY(platform.request("sdram"),
                                           sys_clk_freq)
        self.add_sdram("sdram",
            phy           = self.sdrphy,
            module        = M12L64322A(sys_clk_freq, "1:1"),
            l2_cache_size = 8192,
        )

        # ----- Ethernet (PHY0) ----------------------------------------
        eth_pads = platform.request("eth", 0)
        self.submodules.ethphy = LiteEthPHYRGMII(
            clock_pads = platform.request("eth_clocks", 0),
            pads       = eth_pads,
            tx_delay   = 0,
        )
        self.add_csr("ethphy")
        self.add_ethernet(phy=self.ethphy, dynamic_ip=True)
        # The above wires up LiteEth's MAC + IP/UDP stack and exposes a
        # firmware-side socket API in LiteX's stock `liteethmac.h`.

        if with_second_eth:
            self.submodules.ethphy1 = LiteEthPHYRGMII(
                clock_pads = platform.request("eth_clocks", 1),
                pads       = platform.request("eth", 1),
                tx_delay   = 0,
            )
            self.add_csr("ethphy1")
            # Second PHY is wired but unused by default — left here so a
            # future revision can stream audio + control on separate
            # subnets.

        # ----- LinkPacketFilter ---------------------------------------
        # Sits on the MAC RX path; tags packets that match one of the
        # three Link protocol headers so firmware can fast-dispatch.
        self.submodules.link_filter = LinkPacketFilter()
        self.add_csr("link_filter")
        self.comb += [
            self.link_filter.sink.valid.eq(self.ethmac.interface.sink.valid),
            self.link_filter.sink.last .eq(self.ethmac.interface.sink.last),
            self.link_filter.sink.data .eq(self.ethmac.interface.sink.data),
        ]
        self.irq.add("link_filter", use_loc_if_exists=True)

        # ----- GhostTimeUnit ------------------------------------------
        self.submodules.ghost_time = GhostTimeUnit(sys_clk_freq=sys_clk_freq)
        self.add_csr("ghost_time")

        # ----- BeatPulseGen -------------------------------------------
        self.submodules.beat_pulse = BeatPulseGen(
            sys_clk_freq = sys_clk_freq,
            ghost_time   = self.ghost_time,
        )
        self.add_csr("beat_pulse")

        pulse_pads = platform.request("link_pulse", 0)
        # Only the six critical pulses are pinned on `pmodh` (see
        # platform_i9.py for the rationale). The remaining pulses are
        # still computed by BeatPulseGen for software readback / future
        # pin-outs but are not driven externally.
        self.comb += [
            pulse_pads.clk_24ppqn.eq(self.beat_pulse.pulses.clk_24),
            pulse_pads.beat_clk  .eq(self.beat_pulse.pulses.beat),
            pulse_pads.start     .eq(self.beat_pulse.pulses.start),
            pulse_pads.stop      .eq(self.beat_pulse.pulses.stop),
            pulse_pads.run_level .eq(self.beat_pulse.pulses.run),
            pulse_pads.sync_led  .eq(self.beat_pulse.pulses.sync_led),
        ]

        # ----- TDM16 cores --------------------------------------------
        # Physical ports first, then virtual ones. Each is named
        # `tdm{i}` so firmware can iterate by index.
        for i in range(self.num_physical_tdm_ports):
            pads = platform.request("link_tdm", i)
            core = TDM16Core(
                pads          = pads,
                sample_width  = 16,
                fs_hz         = 48000,
                audio_cd_name = "audio",
                virtual       = False,
                index         = i,
            )
            setattr(self.submodules, f"tdm{i}", core)
            self.add_csr(f"tdm{i}")
            self.irq.add(f"tdm{i}", use_loc_if_exists=True)

        for j in range(self.num_virtual_tdm_ports):
            i = self.num_physical_tdm_ports + j
            core = TDM16Core(
                pads          = None,
                sample_width  = 16,
                fs_hz         = 48000,
                audio_cd_name = "audio",
                virtual       = True,
                index         = i,
            )
            setattr(self.submodules, f"tdm{i}", core)
            self.add_csr(f"tdm{i}")
            self.irq.add(f"tdm{i}", use_loc_if_exists=True)

        # Tell the firmware (via a constant in the generated CSR header)
        # how many TDM ports there are and which are virtual, so it can
        # iterate without recompiling.
        self.add_constant("LINK_NUM_TDM_PORTS",          num_tdm_ports)
        self.add_constant("LINK_NUM_PHYSICAL_TDM_PORTS", num_physical_tdm_ports)
        self.add_constant("LINK_NUM_VIRTUAL_TDM_PORTS",  self.num_virtual_tdm_ports)
        self.add_constant("LINK_TDM_CHANNELS_PER_PORT",  16)
        self.add_constant("LINK_TDM_SAMPLE_WIDTH",       16)
        self.add_constant("LINK_TDM_FS_HZ",              48000)
