"""
TDM16Core — 16-channel × 16-bit TDM serialiser/deserialiser, with a
CPU-visible double-buffered sample register file.

One TDM frame = 16 slots × 16 bits = 256 BCK cycles. At fs = 48 kHz that's
BCK = 12.288 MHz. The serialiser is clocked from the `audio` clock domain
(24.576 MHz MCLK / 2 = 12.288 MHz BCK by toggling each cycle), while the
sample register file lives in the `sys` domain and uses a tiny gray-coded
handshake to safely cross domains.

Each port exposes:

  CSR: CTRL                8 bits  RW  bit0=enable, bit1=loopback, bit2=virtual
       FRAME_COUNT        32 bits  R   monotonic frame counter
       RX_SAMPLES[0..15]  16 bits  R   most-recent samples (one per channel)
       TX_SAMPLES[0..15]  16 bits  RW  samples to be sent on next frame
       IRQ                 — fires once per frame; firmware reads RX_SAMPLES
                              and writes TX_SAMPLES inside the handler

Virtual mode (no physical pads):
  When the core is instantiated with `virtual=True`, no BCK/FS/SDIN/SDOUT
  signals are generated; the IRQ is driven from a sys-clock-domain
  fs-divider so that the firmware still sees a regular 48 kHz tick. The
  RX_SAMPLES register pretends the inputs are zero (or, optionally,
  loopback-from-TX). This makes virtual ports useful as software-only
  audio-routing endpoints.
"""

from migen import (
    Array, ClockDomain, ClockDomainsRenamer, Constant, If, Module, Signal,
)
from migen.genlib.cdc import MultiReg

from litex.soc.interconnect.csr import AutoCSR, CSRStatus, CSRStorage
from litex.soc.interconnect.csr_eventmanager import (
    EventManager, EventSourceProcess,
)


CHANNELS = 16
SLOT_WIDTH = 16
FRAME_BITS = CHANNELS * SLOT_WIDTH      # 256


class TDM16Core(Module, AutoCSR):
    def __init__(self, pads, sample_width=16, fs_hz=48000,
                 audio_cd_name="audio", virtual=False, index=0):
        assert sample_width == SLOT_WIDTH, "TDM16 currently fixed at 16-bit slots"
        self.virtual = virtual
        self.index   = index

        # ---- CSRs ---------------------------------------------------
        self.ctrl        = CSRStorage(8, description=
            "bit0=enable bit1=loopback bit2=force_virtual", reset=0x01)
        self.frame_count = CSRStatus(32, description="frame counter")

        self.rx_samples = []
        self.tx_samples = []
        for ch in range(CHANNELS):
            rx = CSRStatus(SLOT_WIDTH, name=f"rx_ch{ch}",
                           description=f"latest sample, channel {ch}")
            tx = CSRStorage(SLOT_WIDTH, name=f"tx_ch{ch}",
                            description=f"sample to send next frame, channel {ch}")
            setattr(self, f"rx_ch{ch}", rx)
            setattr(self, f"tx_ch{ch}", tx)
            self.rx_samples.append(rx)
            self.tx_samples.append(tx)

        self.submodules.ev = EventManager()
        self.ev.frame = EventSourceProcess()
        self.ev.finalize()

        frame_cnt = Signal(32)
        frame_pulse_sys = Signal()       # one sys-cycle pulse, end of frame

        if not virtual and pads is not None:
            self._make_physical_serdes(pads, audio_cd_name, frame_pulse_sys)
        else:
            self._make_virtual(fs_hz, frame_pulse_sys)

        self.sync += [
            If(frame_pulse_sys,
                frame_cnt.eq(frame_cnt + 1),
            ),
        ]
        self.comb += [
            self.frame_count.status.eq(frame_cnt),
            self.ev.frame.trigger.eq(frame_pulse_sys),
        ]

    # ----------------------------------------------------------------
    def _make_physical_serdes(self, pads, audio_cd_name, frame_pulse_sys):
        """A real TDM16 serialiser/deserialiser running in the audio CD.

        Strategy: each frame cycles through 16 slots × 16 bits. We keep
        a 16-bit `tx_shift` register loaded from `tx_hold[slot]` at the
        start of each slot, and shift it out MSB-first; symmetrically,
        we shift `sdin` into `rx_shift` and write `rx_shift` into
        `rx_lat[slot]` at the end of each slot. BCK is generated by
        toggling each audio cycle, so the effective serial clock is
        `audio / 2 = 12.288 MHz`.
        """

        # Capture the live tx samples in the sys CD; cross to audio CD via
        # a small holding register array.
        tx_hold = [Signal(SLOT_WIDTH) for _ in range(CHANNELS)]
        for ch in range(CHANNELS):
            self.specials += MultiReg(
                self.tx_samples[ch].storage, tx_hold[ch],
                odomain=audio_cd_name)
        tx_hold_arr = Array(tx_hold)

        rx_lat     = [Signal(SLOT_WIDTH) for _ in range(CHANNELS)]
        rx_lat_arr = Array(rx_lat)

        bit_idx  = Signal(max=SLOT_WIDTH)        # 0..15
        slot     = Signal(max=CHANNELS)          # 0..15
        bck      = Signal()
        sdout    = Signal()
        sdin_r   = Signal()
        tx_shift = Signal(SLOT_WIDTH)
        rx_shift = Signal(SLOT_WIDTH)
        frame_pulse_audio = Signal()

        sync_audio = getattr(self.sync, audio_cd_name)
        sync_audio += [
            bck.eq(~bck),
            frame_pulse_audio.eq(0),
            If(bck,
                # rising-edge work
                If(bit_idx == 0,
                    # start of a new slot — reload tx, output its MSB
                    tx_shift.eq(tx_hold_arr[slot]),
                    sdout.eq(tx_hold_arr[slot][SLOT_WIDTH - 1]),
                ).Else(
                    sdout.eq(tx_shift[SLOT_WIDTH - 1]),
                    tx_shift.eq(tx_shift << 1),
                ),
                rx_shift.eq((rx_shift << 1) | sdin_r),
                If(bit_idx == (SLOT_WIDTH - 1),
                    rx_lat_arr[slot].eq((rx_shift << 1) | sdin_r),
                    bit_idx.eq(0),
                    If(slot == (CHANNELS - 1),
                        slot.eq(0),
                        frame_pulse_audio.eq(1),
                    ).Else(
                        slot.eq(slot + 1),
                    ),
                ).Else(
                    bit_idx.eq(bit_idx + 1),
                ),
            ),
        ]

        # FS asserts low for the duration of slot 0.
        fs = Signal()
        self.comb += fs.eq(slot != 0)

        # Pads
        self.comb += [
            pads.bck  .eq(bck),
            pads.fs   .eq(fs),
            pads.sdout.eq(sdout),
            pads.mclk .eq(ClockSignal(audio_cd_name)),
        ]
        self.specials += MultiReg(pads.sdin, sdin_r, odomain=audio_cd_name)

        # Cross frame pulse and latched RX samples back to sys CD
        self.specials += MultiReg(frame_pulse_audio, frame_pulse_sys)
        for ch in range(CHANNELS):
            sys_lat = Signal(SLOT_WIDTH)
            self.specials += MultiReg(rx_lat[ch], sys_lat)
            self.comb += self.rx_samples[ch].status.eq(sys_lat)

    # ----------------------------------------------------------------
    def _make_virtual(self, fs_hz, frame_pulse_sys):
        """No pads; generate a periodic frame tick from the sys clock so
        firmware still gets a 48 kHz IRQ."""
        # Period in sys cycles (75 MHz / 48 kHz ≈ 1562)
        sys_clk = 75_000_000   # informational; real value comes from soc.py
        period  = max(2, sys_clk // fs_hz)
        cnt = Signal(max=period)
        self.sync += [
            If(cnt == (period - 1),
                cnt.eq(0),
                frame_pulse_sys.eq(1),
            ).Else(
                cnt.eq(cnt + 1),
                frame_pulse_sys.eq(0),
            ),
        ]
        # Loopback option: copy tx into rx so the firmware sees its own
        # output back next frame.
        for ch in range(CHANNELS):
            self.comb += If(self.ctrl.storage[1],
                self.rx_samples[ch].status.eq(self.tx_samples[ch].storage),
            )


# Imported here to avoid a top-of-file circular when ghost_time imports
# Migen primitives lazily.
from migen import ClockSignal  # noqa: E402
