/*
 * lwIP `netif` driver for LiteEth on the Colorlight i9 v7.2.
 *
 * Talks straight to the ethmac CSRs and the in-FPGA TX/RX slot RAMs
 * exposed by LiteX. The slot layout matches what `libliteeth/udp.c`
 * uses, and the CSR API is the one generated by `add_ethernet()` in
 * the LiteX SoC top-level.
 *
 * The driver runs in NO_SYS=1 mode: `netif_litex_input()` is invoked
 * from the main loop poll, and lwIP's TCP/UDP raw callbacks fire
 * synchronously from inside that call.
 *
 * RX: poll the `ethmac_sram_writer_ev_pending` flag. When set, copy
 * the slot contents into a freshly-allocated PBUF_POOL pbuf, ack the
 * event, advance the slot, and hand the pbuf to lwIP via
 * `ethernet_input()`.
 *
 * TX: lwIP calls `low_level_output()` with a pbuf chain. Wait for the
 * sram_reader to be ready, copy the chain into the next free TX slot,
 * write length, kick.
 */

#include <string.h>

#include <generated/csr.h>
#include <generated/mem.h>
#include <generated/soc.h>

#include "lwip/opt.h"
#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include "lwip/etharp.h"
#include "lwip/ethip6.h"
#include "lwip/snmp.h"
#include "lwip/stats.h"
#include "lwip/netif.h"
#include "netif/ethernet.h"

#include "config.h"

/* These come from the LiteEth ethmac integration. The exact symbol
 * names are emitted into `generated/csr.h` and `generated/mem.h`
 * by LiteX during build. */
#ifndef ETHMAC_RX_SLOTS
#define ETHMAC_RX_SLOTS 2
#endif
#ifndef ETHMAC_TX_SLOTS
#define ETHMAC_TX_SLOTS 2
#endif
#ifndef ETHMAC_SLOT_SIZE
#define ETHMAC_SLOT_SIZE 2048
#endif

#define ETHMAC_EV_SRAM_WRITER 0x1
#define ETHMAC_EV_SRAM_READER 0x1

static struct netif s_netif;
static unsigned int s_tx_slot;
static unsigned int s_rx_slot;

/* ---------------------------------------------------------------- */

static err_t low_level_output(struct netif *netif, struct pbuf *p) {
    (void)netif;
    /* Wait for TX slot ready. */
    while (!(ethmac_sram_reader_ready_read())) { /* spin */ }

    uint8_t *txbuf = (uint8_t *)(ETHMAC_BASE
        + ETHMAC_SLOT_SIZE * (ETHMAC_RX_SLOTS + s_tx_slot));
    unsigned int len = 0;

    for (struct pbuf *q = p; q != NULL; q = q->next) {
        if (len + q->len > ETHMAC_SLOT_SIZE) return ERR_BUF;
        memcpy(txbuf + len, q->payload, q->len);
        len += q->len;
    }

    ethmac_sram_reader_slot_write(s_tx_slot);
    ethmac_sram_reader_length_write(len);
    ethmac_sram_reader_start_write(1);

    s_tx_slot = (s_tx_slot + 1) % ETHMAC_TX_SLOTS;

    LINK_STATS_INC(link.xmit);
    return ERR_OK;
}

static err_t low_level_init(struct netif *netif) {
    netif->hwaddr_len = 6;
    /* Locally-administered MAC, derived deterministically from a
     * seed so the same board always gets the same address. */
    netif->hwaddr[0] = 0x10;
    netif->hwaddr[1] = 0xe2;
    netif->hwaddr[2] = 0xd5;
    netif->hwaddr[3] = 0x00;
    netif->hwaddr[4] = 0x00;
    netif->hwaddr[5] = 0x01;

    netif->mtu = 1500;
    netif->flags = NETIF_FLAG_BROADCAST
                 | NETIF_FLAG_ETHARP
                 | NETIF_FLAG_LINK_UP
                 | NETIF_FLAG_IGMP
                 | NETIF_FLAG_MLD6;

    /* Bring up the LiteEth MAC. */
    ethmac_sram_reader_ev_pending_write(ETHMAC_EV_SRAM_READER);
    ethmac_sram_writer_ev_pending_write(ETHMAC_EV_SRAM_WRITER);
    s_tx_slot = 0;
    s_rx_slot = 0;
    return ERR_OK;
}

static err_t netif_litex_init(struct netif *netif) {
    netif->name[0] = 'e';
    netif->name[1] = '0';
    netif->output      = etharp_output;
    netif->output_ip6  = ethip6_output;
    netif->linkoutput  = low_level_output;
    return low_level_init(netif);
}

/* ---------------------------------------------------------------- */
/* RX poll — call from the main loop. Drains every pending RX slot. */

void netif_litex_input(void) {
    while (ethmac_sram_writer_ev_pending_read() & ETHMAC_EV_SRAM_WRITER) {
        unsigned int rx_slot = ethmac_sram_writer_slot_read();
        unsigned int len     = ethmac_sram_writer_length_read();
        if (len > ETHMAC_SLOT_SIZE) len = ETHMAC_SLOT_SIZE;

        const uint8_t *rxbuf = (const uint8_t *)(ETHMAC_BASE
            + ETHMAC_SLOT_SIZE * rx_slot);

        struct pbuf *p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);
        if (p) {
            uint16_t off = 0;
            for (struct pbuf *q = p; q != NULL; q = q->next) {
                memcpy(q->payload, rxbuf + off, q->len);
                off += q->len;
            }
            LINK_STATS_INC(link.recv);
            if (s_netif.input(p, &s_netif) != ERR_OK) {
                pbuf_free(p);
            }
        } else {
            LINK_STATS_INC(link.memerr);
        }

        ethmac_sram_writer_ev_pending_write(ETHMAC_EV_SRAM_WRITER);
    }
}

/* ---------------------------------------------------------------- */
/* Public bring-up                                                  */

#include "lwip/ip4_addr.h"
#include "lwip/ip6_addr.h"
#include "lwip/dhcp.h"
#include "lwip/autoip.h"

void netif_litex_bringup(void) {
    ip4_addr_t ipaddr, netmask, gw;
    ip4_addr_set_zero(&ipaddr);
    ip4_addr_set_zero(&netmask);
    ip4_addr_set_zero(&gw);

    netif_add(&s_netif, &ipaddr, &netmask, &gw, NULL,
              netif_litex_init, ethernet_input);
    netif_set_default(&s_netif);
    netif_set_up(&s_netif);

    /* DHCPv4 with AutoIP fallback (link-local 169.254.0.0/16). */
    dhcp_start(&s_netif);

    /* IPv6: enable link-local + RA-driven SLAAC. */
    netif_create_ip6_linklocal_address(&s_netif, 1);
    s_netif.ip6_autoconfig_enabled = 1;
}

struct netif *netif_litex_get(void) { return &s_netif; }
