#include "tdm.h"
#include "config.h"

/* The CSR macros generated by LiteX have the port name baked into them
 * (`tdm0_*`, `tdm1_*`, ...). We dispatch on `port` with a switch.
 *
 * NOTE: This file looks repetitive on purpose — the CSR accessors are
 * macros, not callable through a function pointer, so a switch is the
 * cleanest portable way to dispatch.
 */

#define DECL_PORT(N)                                                          \
    static inline uint16_t _rx_p##N(int ch) {                                 \
        switch (ch) {                                                         \
        case  0: return tdm##N##_rx_ch0_read();                               \
        case  1: return tdm##N##_rx_ch1_read();                               \
        case  2: return tdm##N##_rx_ch2_read();                               \
        case  3: return tdm##N##_rx_ch3_read();                               \
        case  4: return tdm##N##_rx_ch4_read();                               \
        case  5: return tdm##N##_rx_ch5_read();                               \
        case  6: return tdm##N##_rx_ch6_read();                               \
        case  7: return tdm##N##_rx_ch7_read();                               \
        case  8: return tdm##N##_rx_ch8_read();                               \
        case  9: return tdm##N##_rx_ch9_read();                               \
        case 10: return tdm##N##_rx_ch10_read();                              \
        case 11: return tdm##N##_rx_ch11_read();                              \
        case 12: return tdm##N##_rx_ch12_read();                              \
        case 13: return tdm##N##_rx_ch13_read();                              \
        case 14: return tdm##N##_rx_ch14_read();                              \
        case 15: return tdm##N##_rx_ch15_read();                              \
        }                                                                     \
        return 0;                                                             \
    }                                                                         \
    static inline void _tx_p##N(int ch, uint16_t v) {                         \
        switch (ch) {                                                         \
        case  0: tdm##N##_tx_ch0_write(v);  break;                            \
        case  1: tdm##N##_tx_ch1_write(v);  break;                            \
        case  2: tdm##N##_tx_ch2_write(v);  break;                            \
        case  3: tdm##N##_tx_ch3_write(v);  break;                            \
        case  4: tdm##N##_tx_ch4_write(v);  break;                            \
        case  5: tdm##N##_tx_ch5_write(v);  break;                            \
        case  6: tdm##N##_tx_ch6_write(v);  break;                            \
        case  7: tdm##N##_tx_ch7_write(v);  break;                            \
        case  8: tdm##N##_tx_ch8_write(v);  break;                            \
        case  9: tdm##N##_tx_ch9_write(v);  break;                            \
        case 10: tdm##N##_tx_ch10_write(v); break;                            \
        case 11: tdm##N##_tx_ch11_write(v); break;                            \
        case 12: tdm##N##_tx_ch12_write(v); break;                            \
        case 13: tdm##N##_tx_ch13_write(v); break;                            \
        case 14: tdm##N##_tx_ch14_write(v); break;                            \
        case 15: tdm##N##_tx_ch15_write(v); break;                            \
        }                                                                     \
    }

#if LINK_NUM_TDM_PORTS >= 1
DECL_PORT(0)
#endif
#if LINK_NUM_TDM_PORTS >= 2
DECL_PORT(1)
#endif
#if LINK_NUM_TDM_PORTS >= 3
DECL_PORT(2)
#endif
#if LINK_NUM_TDM_PORTS >= 4
DECL_PORT(3)
#endif

void tdm_init(void) {
#if LINK_NUM_TDM_PORTS >= 1
    tdm0_ctrl_write(0x01);
#endif
#if LINK_NUM_TDM_PORTS >= 2
    tdm1_ctrl_write(0x01);
#endif
#if LINK_NUM_TDM_PORTS >= 3
    tdm2_ctrl_write(0x01);
#endif
#if LINK_NUM_TDM_PORTS >= 4
    tdm3_ctrl_write(0x01);
#endif
}

uint16_t tdm_read_rx(int port, int channel) {
    switch (port) {
#if LINK_NUM_TDM_PORTS >= 1
    case 0: return _rx_p0(channel);
#endif
#if LINK_NUM_TDM_PORTS >= 2
    case 1: return _rx_p1(channel);
#endif
#if LINK_NUM_TDM_PORTS >= 3
    case 2: return _rx_p2(channel);
#endif
#if LINK_NUM_TDM_PORTS >= 4
    case 3: return _rx_p3(channel);
#endif
    }
    return 0;
}

void tdm_write_tx(int port, int channel, uint16_t sample) {
    switch (port) {
#if LINK_NUM_TDM_PORTS >= 1
    case 0: _tx_p0(channel, sample); break;
#endif
#if LINK_NUM_TDM_PORTS >= 2
    case 1: _tx_p1(channel, sample); break;
#endif
#if LINK_NUM_TDM_PORTS >= 3
    case 2: _tx_p2(channel, sample); break;
#endif
#if LINK_NUM_TDM_PORTS >= 4
    case 3: _tx_p3(channel, sample); break;
#endif
    }
}

uint32_t tdm_frame_count(int port) {
    switch (port) {
#if LINK_NUM_TDM_PORTS >= 1
    case 0: return tdm0_frame_count_read();
#endif
#if LINK_NUM_TDM_PORTS >= 2
    case 1: return tdm1_frame_count_read();
#endif
#if LINK_NUM_TDM_PORTS >= 3
    case 2: return tdm2_frame_count_read();
#endif
#if LINK_NUM_TDM_PORTS >= 4
    case 3: return tdm3_frame_count_read();
#endif
    }
    return 0;
}

static uint32_t s_last_count[LINK_NUM_TDM_PORTS];

int tdm_frame_pending(int port) {
    if (port >= LINK_NUM_TDM_PORTS) return 0;
    uint32_t now = tdm_frame_count(port);
    return now != s_last_count[port];
}

void tdm_clear_frame_pending(int port) {
    if (port >= LINK_NUM_TDM_PORTS) return;
    s_last_count[port] = tdm_frame_count(port);
}
